### ISSUE TITLE
Actividad 8 corregida: Fallo (ver descripción)

### ISSUE THREAD

**Issue by cborcar637** [0xnamelessDev/TIC-2BCN#8]
La descripción de la actividad comenta que deben crearse 2 funciones: `MensajeSwitch` y `MensajeIf` y cada una resuelve el problema de una forma distinta.

Aunque tu código resuelve el problema perfectamente, no estás siguiendo las indicaciones de la actividad. En lugar de usar 2 funciones, usas una y le pasas un parámetro booleano para hacer la bifurcación. No está mal, pero no cumple con los requisitos que establece la actividad. 

Cuando lo resuelvas, no cierres la solicitud. Comenta sobre ella para que yo pueda revisarlo.

**Comment by javierOllerSanchez** [comment]
Ya está revisada la actividad 8

**Comment by cborcar637** [comment]
Revisado
