### ISSUE TITLE
Actividad 9 corregida: Fallo (ver descripción)

### ISSUE THREAD

**Issue by cborcar637** [0xnamelessDev/TIC-2BCN#9]
En el HTML hay un botón que llama a la función `factorial()`, pero en el código no existe ninguna función llamada `factorial()`. Existen 3 funciones y cada una resuelve el problema con un tipo de estructura iterativa. 

El código está bien, pero no llega a ejecutarse ninguna función nunca. Puedes resolverlo cambiando la función a la que llama el botón por una de ellas, o creando 3 botones.

Cuando lo resuelvas, no cierres la solicitud. Comenta sobre ella para que yo pueda revisarlo.

**Comment by javierOllerSanchez** [comment]
Se había sobrescrito el index.html al hacer el pull to origin, ya debería de estar resuelto

**Comment by cborcar637** [comment]
Revisado. Cierro la solicitud
